/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bigtable extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.BigtableRecord> {

	private static final long serialVersionUID = -1714636656;

	/**
	 * The singleton instance of <code>public.bigtable</code>
	 */
	public static final com.ph.jooq.tables.Bigtable BIGTABLE = new com.ph.jooq.tables.Bigtable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.BigtableRecord> getRecordType() {
		return com.ph.jooq.tables.records.BigtableRecord.class;
	}

	/**
	 * The column <code>public.bigtable.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.BigtableRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.bigtable.name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.BigtableRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this);

	/**
	 * The column <code>public.bigtable.age</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.BigtableRecord, java.lang.Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.bigtable.money</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.BigtableRecord, java.math.BigDecimal> MONEY = createField("money", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this);

	/**
	 * Create a <code>public.bigtable</code> table reference
	 */
	public Bigtable() {
		super("bigtable", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.bigtable</code> table reference
	 */
	public Bigtable(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Bigtable.BIGTABLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Bigtable as(java.lang.String alias) {
		return new com.ph.jooq.tables.Bigtable(alias);
	}
}
