/**
 * This class is generated by jOOQ
 */
package com.ph.jooq;


import com.ph.jooq.tables.Bigtable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.bigtable
	 */
	public static final Bigtable BIGTABLE = com.ph.jooq.tables.Bigtable.BIGTABLE;
}
