/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BigtableRecord extends org.jooq.impl.TableRecordImpl<com.ph.jooq.tables.records.BigtableRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Integer, java.math.BigDecimal> {

	private static final long serialVersionUID = -214239527;

	/**
	 * Setter for <code>public.bigtable.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.bigtable.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.bigtable.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.bigtable.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.bigtable.age</code>. 
	 */
	public void setAge(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.bigtable.age</code>. 
	 */
	public java.lang.Integer getAge() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.bigtable.money</code>. 
	 */
	public void setMoney(java.math.BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.bigtable.money</code>. 
	 */
	public java.math.BigDecimal getMoney() {
		return (java.math.BigDecimal) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.math.BigDecimal> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.math.BigDecimal> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.ph.jooq.tables.Bigtable.BIGTABLE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ph.jooq.tables.Bigtable.BIGTABLE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.ph.jooq.tables.Bigtable.BIGTABLE.AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field4() {
		return com.ph.jooq.tables.Bigtable.BIGTABLE.MONEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value4() {
		return getMoney();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BigtableRecord
	 */
	public BigtableRecord() {
		super(com.ph.jooq.tables.Bigtable.BIGTABLE);
	}

	/**
	 * Create a detached, initialised BigtableRecord
	 */
	public BigtableRecord(java.lang.Integer id, java.lang.String name, java.lang.Integer age, java.math.BigDecimal money) {
		super(com.ph.jooq.tables.Bigtable.BIGTABLE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, age);
		setValue(3, money);
	}
}
